runtime: go114

main: ./cmd/backend

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index\.html

  - url: /static
    static_dir: static

  - url: /.*
    script: auto
    secure: always
